Repository AY2122S1-CS2113T-F11-1/tp, pull requests merged in 2021-10, with the labels that each got.

#48 JUnit test for Module Class added
  src/main/java/module/Module.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/module/ModuleTest.java
Labels: type.Task

#52 Branch update parser
  src/main/java/command/NoCap.java
  src/main/java/command/Parser.java
  src/main/java/command/TaskList.java
  src/main/java/module/Module.java
  src/main/java/module/ModuleList.java
Labels: type.Task

#60 Add LocalDateTime to Tasks
  src/main/java/command/Parser.java
  src/main/java/command/Ui.java
  src/main/java/module/Module.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/task/Task.java
  src/main/java/task/TaskList.java
  src/test/java/module/ModuleTest.java
  src/test/java/task/TaskListTest.java
Labels: type.Task

#81 Change TaskList Methods and Added to Parser, Add logger for TaskList
  src/main/java/command/Parser.java
  src/main/java/command/Ui.java
  src/main/java/task/TaskList.java
  src/test/java/task/TaskListTest.java
Labels: enhancement, type.Task

#84 Branch assertions logger cleaner code
  src/main/java/command/Parser.java
  src/main/java/module/Module.java
  src/main/java/module/ModuleList.java
  src/main/java/module/Schedule.java
Labels: type.Task

#95 Add MarkDone to Parser
  src/main/java/command/Parser.java
  src/main/java/command/Ui.java
  src/main/java/task/Task.java
Labels: type.Task

#106 clean up parser class
  src/main/java/command/Parser.java
  src/main/java/task/Task.java
  src/main/java/task/TaskList.java
Labels: type.Task

#112 Branch JUnit-3
  META-INF/MANIFEST.MF
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/command/NoCap.java
  src/main/java/command/Ui.java
  src/main/java/command/parser/DateParser.java
  src/main/java/command/parser/ListParser.java
  src/main/java/command/parser/Parser.java
  src/main/java/task/Task.java
  src/main/java/task/TaskList.java
  src/test/java/task/TaskListTest.java
  src/test/java/task/TaskTest.java
  text-ui-test/runtest.sh
Labels: bug

#144 add parser commands
  src/main/java/command/parser/ListParser.java
  src/main/java/command/parser/Parser.java
Labels: type.Task

#267 Branch bug 3.0
  docs/UserGuide.md
  src/main/java/command/Ui.java
  src/main/java/command/parser/Command.java
  src/main/java/task/TaskList.java
Labels: bug

#269 Edit UG
  docs/UserGuide.md
Labels: bug, documentation

#272 Updated UG
  docs/UserGuide.md
  docs/media/GradableTaskOutput.jpg
Labels: bug, documentation
